services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        command: >
            sh -lc "mkdir -p storage/logs bootstrap/cache &&
                    chmod -R 777 storage bootstrap/cache &&
                    php-fpm"
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - app

    db:
        image: mysql:8.4
        restart: always
        environment:
            MYSQL_DATABASE: tech_test
            MYSQL_USER: user
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
